blank_issues_enabled: false
contact_links:
  - name: Planning Center Support
    url: https://support.planningcenteronline.com
    about: Not a developer? Get general Planning Center help from our support team.
