blank_issues_enabled: false
contact_links:
  - name: Report a Security Vulnerability
    url: https://www.planningcenter.com/security
    about: Please do not post security vulnerabilities here. To securely report a vulnerability, please follow the steps on our security page. Thank you!
  - name: Planning Center Support
    url: https://support.planningcenter.com
    about: Not an API specific question? Get general Planning Center help from our support team.
